### ISSUE TITLE
Fire OnChange() only when something changed

### ISSUE THREAD

**Issue by IbrahimHd** [g1eb/angular-datetime-range#3]
Hi Gleb,

I have noticed that the `OnChange()` is being fired in all cases, do you agree that it's more reasonable to close the edit menu but not to call  `OnChange()` if "start or end" does not changed.

Thanks

**Comment by g1eb** [comment]
Yes, I agree with you that ```onChange()``` should be fire only when something is changed.0

I've checked and it seems to work fine, are you seeing ```onChange()``` firing when nothing is changed?

**Comment by IbrahimHd** [comment]
Yes Gleb, `onChange()` is fired even if nothing has been changed!

**Comment by g1eb** [comment]
Hmm, very strange! Does this also happen for you on the [demo](https://rawgit.com/g1eb/angular-datetime-range/master/) page?

I'd love to look into this but I can't reproduce this issue here. Could you please provide a snippet of the environment where you are using this directive? Maybe a [jsbin](https://jsbin.com/) or something like that?

Thank you in advance!

**Comment by IbrahimHd** [comment]
the issue has no longer appeared. It seems it was a cashing issue with the old version.

Job done!
